### ISSUE TITLE
A rust compilation error for Ubuntu 22.04

### ISSUE THREAD

**Issue by iihihiuh** [intel/tdx-tools#536]
When compiling the 2023ww41 version, during compiling v0.10.7, rust gives us a compiler error:

Compiling digest v0.10.7
error[E0599]: no method named `as_encoded_bytes` found for reference `&OsStr` in the current scope
   --> /home/yongqin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:186:26

I believe the method "as_encoded_bytes" has been added to Rust fairly recently. I updated my rustc to version 1.78. However, after I rerun the build_repo.sh, my rustc version is reverted back to 1.74 nightly.

Could anyone help me to resolve this issue and why rustc version is reverted to 1.74 after running the script?

**Comment by kpadwal** [comment]
I have noticed the same issue. Is there a solution available?

**Comment by tingyuz** [comment]
Same problem with me. As a result, we don't have host_repo and guest_repo folders.

**Comment by iihihiuh** [comment]
I was also trying to recompile the kernel using older versions of the TDX tools. However, many Git repositories are missing due to the changes in their GitHub repository structures. I hope someone in the development team help us resolve this issue.

**Comment by tingyuz** [comment]
I have tried to recompile both tdx-tool 1.0 and 1.5 on GitHub. Unfortunately neither works currently. Looking for some guidance if possible. Thanks!

**Comment by jialeif** [comment]
> I was also trying to recompile the kernel using older versions of the TDX tools. However, many Git repositories are missing due to the changes in their GitHub repository structures. I hope someone in the development team help us resolve this issue.

Thanks! Regarding the issues of missing git repo in older tdx-tools, because the latest Ubuntu distribution grub and shim have built-in TDX measurement patches, and we have verified them, downstream tdx-guest-shim and tdx-guest-grub2 are no longer needed.
We removed the 2 repos https://github.com/intel/shim-tdx/ and https://github.com/intel/grub-tdx/. The newer version tdx-tools https://github.com/intel/tdx-tools/releases/tag/2023ww41 will not build tdx-guest-shim and tdx-guest-grub2 for Ubuntu.

**Comment by kpadwal** [comment]
Thanks @jialeif.
Due to the issue we encountered, we are unable to build the latest tdx-tool available at https://github.com/intel/tdx-tools/releases/tag/2023ww41. Could you please guide us on how to proceed?

**Comment by iihihiuh** [comment]
> > I was also trying to recompile the kernel using older versions of the TDX tools. However, many Git repositories are missing due to the changes in their GitHub repository structures. I hope someone in the development team help us resolve this issue.
> 
> Thanks! Regarding the issues of missing git repo in older tdx-tools, because the latest Ubuntu distribution grub and shim have built-in TDX measurement patches, and we have verified them, downstream tdx-guest-shim and tdx-guest-grub2 are no longer needed. We removed the 2 repos https://github.com/intel/shim-tdx/ and https://github.com/intel/grub-tdx/. The newer version tdx-tools https://github.com/intel/tdx-tools/releases/tag/2023ww41 will not build tdx-guest-shim and tdx-guest-grub2 for Ubuntu.

Thank you @jialeif. After commenting out `build_shim` and `build_grub` lines in the `build-repo.sh`, I am able to build a older version of the kernel and boot my machine with TDX on.

**Comment by iihihiuh** [comment]
> When compiling the 2023ww41 version, during compiling v0.10.7, rust gives us a compiler error:
> 
> Compiling digest v0.10.7 error[E0599]: no method named `as_encoded_bytes` found for reference `&OsStr` in the current scope --> /home/yongqin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:186:26
> 
> I believe the method "as_encoded_bytes" has been added to Rust fairly recently. I updated my rustc to version 1.78. However, after I rerun the build_repo.sh, my rustc version is reverted back to 1.74 nightly.
> 
> Could anyone help me to resolve this issue and why rustc version is reverted to 1.74 after running the script?

But the newest version kernel still does have the rust built issue.

**Comment by kpadwal** [comment]
> > > I was also trying to recompile the kernel using older versions of the TDX tools. However, many Git repositories are missing due to the changes in their GitHub repository structures. I hope someone in the development team help us resolve this issue.
> > 
> > 
> > Thanks! Regarding the issues of missing git repo in older tdx-tools, because the latest Ubuntu distribution grub and shim have built-in TDX measurement patches, and we have verified them, downstream tdx-guest-shim and tdx-guest-grub2 are no longer needed. We removed the 2 repos https://github.com/intel/shim-tdx/ and https://github.com/intel/grub-tdx/. The newer version tdx-tools https://github.com/intel/tdx-tools/releases/tag/2023ww41 will not build tdx-guest-shim and tdx-guest-grub2 for Ubuntu.
> 
> Thank you @jialeif. After commenting out `build_shim` and `build_grub` lines in the `build-repo.sh`, I am able to build a older version of the kernel and boot my machine with TDX on.

Yes, I have observed the same.
but not able to SSH to the guest from the host.

ssh -p10026 root@localhost
root@localhost: Permission denied (publickey).

**Comment by iihihiuh** [comment]
> > > > I was also trying to recompile the kernel using older versions of the TDX tools. However, many Git repositories are missing due to the changes in their GitHub repository structures. I hope someone in the development team help us resolve this issue.
> > > 
> > > 
> > > Thanks! Regarding the issues of missing git repo in older tdx-tools, because the latest Ubuntu distribution grub and shim have built-in TDX measurement patches, and we have verified them, downstream tdx-guest-shim and tdx-guest-grub2 are no longer needed. We removed the 2 repos https://github.com/intel/shim-tdx/ and https://github.com/intel/grub-tdx/. The newer version tdx-tools https://github.com/intel/tdx-tools/releases/tag/2023ww41 will not build tdx-guest-shim and tdx-guest-grub2 for Ubuntu.
> > 
> > 
> > Thank you @jialeif. After commenting out `build_shim` and `build_grub` lines in the `build-repo.sh`, I am able to build a older version of the kernel and boot my machine with TDX on.
> 
> Yes, I have observed the same. but not able to SSH to the guest from the host.
> 
> ssh -p10026 root@localhost root@localhost: Permission denied (publickey).

This is the issue related to the sshd_config in the VM image. We should modify std-guest-stack.sh to allow root login with passcode.

**Comment by Shubakara** [comment]
Hi,

I have encountered the following errors while building TDX1.5 2023ww41 build any idea on how to resolve this issue ?



error[E0599]: no method named `as_encoded_bytes` found for reference `&OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:186:26
    |
186 |         let bytes = self.as_encoded_bytes();
    |                          ^^^^^^^^^^^^^^^^ method not found in `&OsStr`

error[E0599]: no method named `as_encoded_bytes` found for reference `&OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:195:26
    |
195 |         let bytes = self.as_encoded_bytes();
    |                          ^^^^^^^^^^^^^^^^ method not found in `&OsStr`

error[E0599]: no method named `as_encoded_bytes` found for reference `&OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:201:26
    |
201 |         let bytes = self.as_encoded_bytes();
    |                          ^^^^^^^^^^^^^^^^ method not found in `&OsStr`

error[E0599]: no function or associated item named `from_encoded_bytes_unchecked` found for struct `OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:206:29
    |
206 |             unsafe { OsStr::from_encoded_bytes_unchecked(s) }
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `OsStr`

error[E0599]: no method named `as_encoded_bytes` found for reference `&OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:210:26
    |
210 |         let bytes = self.as_encoded_bytes();
    |                          ^^^^^^^^^^^^^^^^ method not found in `&OsStr`

error[E0599]: no method named `as_encoded_bytes` found for reference `&OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:225:29
    |
225 |         let haystack = self.as_encoded_bytes();
    |                             ^^^^^^^^^^^^^^^^ method not found in `&OsStr`

error[E0599]: no function or associated item named `from_encoded_bytes_unchecked` found for struct `OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:233:24
    |
233 |                 OsStr::from_encoded_bytes_unchecked(first),
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `OsStr`

error[E0599]: no function or associated item named `from_encoded_bytes_unchecked` found for struct `OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:234:24
    |
234 |                 OsStr::from_encoded_bytes_unchecked(second),
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `OsStr`

error[E0599]: no method named `as_encoded_bytes` found for reference `&OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:278:20
    |
278 |     let bytes = os.as_encoded_bytes();
    |                    ^^^^^^^^^^^^^^^^ method not found in `&OsStr`

error[E0599]: no function or associated item named `from_encoded_bytes_unchecked` found for struct `OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:281:16
    |
281 |         OsStr::from_encoded_bytes_unchecked(first),
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `OsStr`

error[E0599]: no function or associated item named `from_encoded_bytes_unchecked` found for struct `OsStr` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_lex-0.7.0/src/ext.rs:282:16
    |
282 |         OsStr::from_encoded_bytes_unchecked(second),
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `OsStr`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `clap_lex` (lib) due to 11 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by ruomengh** [comment]
Thanks for raising the issue. The project is end of life. Please refer to Red Hat blog [Enabling hardware-backed confidential computing with a CentOS SIG](https://www.redhat.com/en/blog/enabling-hardware-backed-confidential-computing-centos-sig) or Ubuntu blog [Intel® TDX 1.0 technology preview available on Ubuntu 23.10](https://ubuntu.com/blog/intel-tdx-1-0-preview-on-ubuntu-23-10) or SUSE blog [Intel® TDX Support Coming to SUSE Linux Enterprise Server](https://www.suse.com/c/intel-tdx-support-coming-to-suse-linux-enterprise-server/) for more information of TDX Early Preview.
